# Generated by Django 6.0.2 on 2026-03-03 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='movie',
        ),
    ]
