# Generated by Django 6.0.2 on 2026-03-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmax', '0002_remove_booking_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
