# Generated by Django 6.0.2 on 2026-03-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmax', '0003_alter_show_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.TimeField(),
        ),
    ]
